# Generated by Django 2.2.11 on 2020-03-15 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(related_name='blog_followers', to=settings.AUTH_USER_MODEL)),
                ('read_posts', models.ManyToManyField(to='posts.Post')),
                ('subscriptions', models.ManyToManyField(related_name='blog_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
