# Generated by Django 2.2.11 on 2020-03-15 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_personalblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalblog',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='blog_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalblog',
            name='read_posts',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='personalblog',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='blog_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
