version: '3'

services:
  web:
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - .:/app
   ports:
     - "8000:8000"

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A news_project worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
